[2023-10-24 16:58:26,360] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:58:24.575637+00:00 [queued]>
[2023-10-24 16:58:26,391] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:58:24.575637+00:00 [queued]>
[2023-10-24 16:58:26,392] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-24 16:58:26,404] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-10-24 16:58:26,405] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-24 16:58:26,445] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2023-10-24 16:58:24.575637+00:00
[2023-10-24 16:58:26,453] {standard_task_runner.py:52} INFO - Started process 315 to run task
[2023-10-24 16:58:26,460] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'manual__2023-10-24T16:58:24.575637+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpbbflb31r', '--error-file', '/tmp/tmp9jew48m1']
[2023-10-24 16:58:26,462] {standard_task_runner.py:80} INFO - Job 57: Subtask create_table
[2023-10-24 16:58:26,610] {task_command.py:371} INFO - Running <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:58:24.575637+00:00 [running]> on host 0d4d602ef8f0
[2023-10-24 16:58:26,832] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Alex
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-10-24T16:58:24.575637+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-24T16:58:24.575637+00:00
[2023-10-24 16:58:26,852] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-10-24 16:58:26,892] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS test.vacancy_test(
            id INT PRIMARY KEY,
            name VARCHAR(50)), parameters: None
[2023-10-24 16:58:26,904] {postgres.py:94} INFO - NOTICE:  relation "vacancy_test" already exists, skipping

[2023-10-24 16:58:26,931] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20231024T165824, start_date=20231024T165826, end_date=20231024T165826
[2023-10-24 16:58:26,992] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-24 16:58:27,078] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
