[2023-10-24 16:56:21,505] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:56:19.939728+00:00 [queued]>
[2023-10-24 16:56:21,528] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:56:19.939728+00:00 [queued]>
[2023-10-24 16:56:21,529] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-24 16:56:21,533] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-10-24 16:56:21,534] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-24 16:56:21,562] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2023-10-24 16:56:19.939728+00:00
[2023-10-24 16:56:21,571] {standard_task_runner.py:52} INFO - Started process 238 to run task
[2023-10-24 16:56:21,575] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_table', 'manual__2023-10-24T16:56:19.939728+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpxz8euxy3', '--error-file', '/tmp/tmpdzqi409k']
[2023-10-24 16:56:21,577] {standard_task_runner.py:80} INFO - Job 56: Subtask create_table
[2023-10-24 16:56:21,733] {task_command.py:371} INFO - Running <TaskInstance: postgres_dag.create_table manual__2023-10-24T16:56:19.939728+00:00 [running]> on host 0d4d602ef8f0
[2023-10-24 16:56:21,901] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Alex
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-10-24T16:56:19.939728+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-24T16:56:19.939728+00:00
[2023-10-24 16:56:21,919] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-10-24 16:56:21,951] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS test.vacancy_test(
            id INT PRIMARY KEY,
            name VARCHAR(50)), parameters: None
[2023-10-24 16:56:21,967] {postgres.py:94} INFO - NOTICE:  relation "vacancy_test" already exists, skipping

[2023-10-24 16:56:22,000] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20231024T165619, start_date=20231024T165621, end_date=20231024T165622
[2023-10-24 16:56:22,070] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-24 16:56:22,152] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
